export const testIds = {
    productGrid: 'product-grid',
    productCard: (id: string) => `product-card-${id}`,
    addToCart: (id: string) => `add-to-cart-${id}`,
    cartCount: 'cart-count',
    cartItem: (id: string) => `cart-item-${id}`,
    checkoutSubmit: 'checkout-submit',
    confirmation: 'confirmation',
    brokenTrigger: (scenarioId: string) => `trigger-${scenarioId}`,
    logTrigger: (scenarioId: string) => `log-trigger-${scenarioId}`,
    httpTrigger: (scenarioId: string) => `http-trigger-${scenarioId}`,
    httpResult: 'http-result',
    boundaryFallback: 'boundary-fallback',
    boundaryReset: 'boundary-reset',
} as const;
