import { ErrorOrigin } from './types';

export const MAX_HIERARCHY_DEPTH = 200;

export const DEFAULT_PROPS_DENYLIST =
    /password|passwd|pwd|token|secret|authorization|\bauth\b|credentials?|cookie|api[-_]?key|session|csrf|xsrf/i;

export const INFO_TO_ORIGIN: Record<string, ErrorOrigin> = {
    // Development strings
    'setup function': 'setup',
    'render function': 'render',
    'component update': 'render',
    'watcher getter': 'watcher',
    'watcher callback': 'watcher',
    'watcher cleanup function': 'watcher',
    'native event handler': 'event',
    'component event handler': 'event',
    'beforeCreate hook': 'lifecycle',
    'created hook': 'lifecycle',
    'beforeMount hook': 'lifecycle',
    'mounted hook': 'lifecycle',
    'beforeUpdate hook': 'lifecycle',
    'updated hook': 'lifecycle',
    'beforeUnmount hook': 'lifecycle',
    'unmounted hook': 'lifecycle',
    'activated hook': 'lifecycle',
    'deactivated hook': 'lifecycle',
    'errorCaptured hook': 'lifecycle',
    'renderTracked hook': 'lifecycle',
    'renderTriggered hook': 'lifecycle',
    'serverPrefetch hook': 'lifecycle',
    'vnode hook': 'lifecycle',
    'directive hook': 'lifecycle',
    'transition hook': 'lifecycle',
    'ref function': 'setup',
    'async component loader': 'setup',
    'scheduler flush': 'render',
    'app errorHandler': 'lifecycle',
    'app warnHandler': 'lifecycle',
    'app unmount cleanup function': 'lifecycle',

    // Production codes
    '0': 'setup',
    '1': 'render',
    '2': 'watcher',
    '3': 'watcher',
    '4': 'watcher',
    '5': 'event',
    '6': 'event',
    '7': 'lifecycle',
    '8': 'lifecycle',
    '9': 'lifecycle',
    '10': 'lifecycle',
    '11': 'lifecycle',
    '12': 'setup',
    '13': 'setup',
    '14': 'render',
    '15': 'render',
    '16': 'lifecycle',
    'sp': 'lifecycle',
    'bc': 'lifecycle',
    'c': 'lifecycle',
    'bm': 'lifecycle',
    'm': 'lifecycle',
    'bu': 'lifecycle',
    'u': 'lifecycle',
    'bum': 'lifecycle',
    'um': 'lifecycle',
    'a': 'lifecycle',
    'da': 'lifecycle',
    'ec': 'lifecycle',
    'rtc': 'lifecycle',
    'rtg': 'lifecycle',
};
